import {Hero} from './hero';

export const HEROES: Hero[] = [
    {id: 1,  image: 'superman.jpg'       , name: 'Superman'       , description:'Kal-El was born on the doomed planet Krypton to Jor-El and Lara. Although Jor-El had hoped to send his pregnant wife away from the planet in a test rocket and avoid its destruction, Kal-El was born earlier than expected, and the life support systems could only support one. Therefore, the baby was sent alone to Earth, the last son of Krypton.\r\n\r\nThe baby´s spaceship landed in Sutton Field near Smallville, Kansas, where he was found by Jonathan and Martha Kent, who raised him as their son, Clark Kent. As he grew older, he began exhibiting extraordinary powers, including super-strength and flight.' },
    {id: 2,  image: 'batman.jpg'         , name: 'Batman'         , description:'When leaving from a movie theater and back to home, Thomas and Martha Wayne are accompanied by their 8-year-old son, Bruce. However, unknown to them they would see their only son for one short last moment. Stepping into Park row (now called Crime Alley) out of the shadows is a masked gunman who killed both, Thomas and Martha. While their 8-year-old son watched their brutal death take place, Bruce´s life would never be the same. At that moment, Bruce made a solemn oath to be an avenger of the knight and fight crime. That moment, Bruce Wayne died and Batman was born! Batman is the World´s Greatest Detective and can handle any problem. He´s one of the greatest heroes the world will ever know. Batman! ' },
    {id: 3,  image: 'spiderman.jpg'      , name: 'Spiderman'      , description:'One evening, Parker attended a public exhibition demonstrating the safe handling of nuclear laboratory waste materials sponsored by the General Techtronics Corporation. During the demonstration, a small common house spider happened to be in the path of a particle accelerator´s beam and was massively irradiated. The stricken spider fell on to Parker´s hand, broke his skin with its fangs, and died.' },
    {id: 4,  image: 'thor.jpg'           , name: 'Thor'           , description:'Descended from Norse gods, Thor had many adventures in Earth´s past. Around the year 1000 CE, he faced Hercules and time travelling Greek warriors, the vampire Varnae, the Annunaki deity Marduk, the troll Grylak the Greater, giant rats in an Atlantean outpost, visted the sons of one of the men killed by the rats, and battled Dromedan. Thor also lived as the humans Sigurd and Siegfried, slaying the dragon Fafnir.' },
    {id: 5,  image: 'captainamerica.jpg' , name: 'Captain America', description:'Captain America represented the pinnacle of human physical perfection. He experienced a time when he was augmented to superhuman levels, but generally performed just below superhuman levels for most of his career. Captain America had a very high intelligence as well as agility, strength, speed, endurance, and reaction time superior to any Olympic athlete who ever competed. The Super-Soldier formula that he had metabolized had enhanced all of his bodily functions to the peak of human efficiency. Most notably, his body eliminates the excessive build-up of fatigue-producing poisons in his muscles, granting him phenomenal endurance.' },
    {id: 6,  image: 'catwoman.jpg'       , name: 'Catwoman'       , description:'Selina Kyle´s early life was defined by tragedy. When she was just a girl, her brutalized mother Maria committed suicide and her violent father Brian drank himself to death not long after. Separated from her younger sister Magdalena and remanded to the Sprang Hall Juvenile Detention Center, an abusive state home for orphaned or delinquent girls, she opted instead to take her chances on the streets of Gotham City.' },
    {id: 7,  image: 'robin.jpg'          , name: 'Robin'          , description:'For many years, Richard \"Dick\" Grayson was Batman´s sidekick Robin. The name \"Robin the Boy Wonder\" and the medieval look of the original costume were inspired by the legendary hero Robin Hood, as well as the red-breasted American Robin, which continued the \"flying animal\" motif of Batman.\r\n\r\nYoung Dick Grayson was born on the first day of spring. His mother nicknamed him \"little Robin\". Little did she know how prophetic this term of endearment would be in her son´s life. ' },
    {id: 8,  image: 'hulk.jpg'           , name: 'Hulk'           , description:'Supervising the trial of an experimental gamma bomb that he designed for the U.S. Defense Department at a nuclear research facility in New Mexico, Bruce selflessly rushed to the rescue of an ignorant teenager who had wandered onto the testing field as the countdown ticked inexorably toward zero. After shoving young Rick Jones to safety in a nearby ditch, Bruce was struck full-force by the bomb blast. He survived, but was irradiated by the deadly gamma energy. ' },
    {id: 9,  image: 'ironman.jpg'        , name: 'Ironman'        , description:'Anthony Stark, son of industrialist and inventor Howard Stark, demonstrated his mechanical aptitude and extraordinary inventive genius at a very early age, enrolling in the undergraduate electrical engineering program at the Massachusetts Institute of Technology at the age of 15. Double majors in physics and engineering were easy for him. When he was 21, he inherited his father´s business, Stark Industries, and within a few years turned it into a multi-billion dollar industry complex whose chief contracts were for weaponry and munitions for the U.S. government.' },
    {id: 10, image: 'deadpool.jpg'       , name: 'Deadpool'       , description:'Not too much is known about Deadpool´s childhood. Sometime after his mother died from cancer, his father was killed by a drunken friend, and he was kicked out of the United States Army Special Forces, \"Wade\" joined Project X. Little was known of Wilson´s subsequent mercenary activities. ' },
    {id: 11, image: 'songoku.jpg'        , name: 'Son Goku'       , description:'Kakarot was found by an old man named Gohan in a small space craft. Gohan tried to raise the young boy, but Kakarot was extremely hostile and strong by human standards. During a trip one day, young Kakarotto fell down a deep ravine and bashed his head. The permanent amnesia from this fall prevented the young boy from completing his initial mission. He was named Son Goku by Gohan. ' },
    {id: 11, image: 'wonderwoman.jpg'    , name: 'Wonder Woman'   , description:'Wonder Woman did not keep her identity a secret, and she was not at first a \"super-heroine\". Indeed, her character was in many ways that of a babe in the woods, innocent and without guile. Diana spoke only Themyscirian, a combination of classical Greek and Turkish. She had to learn English when she arrived in America, rather than knowing the language intuitively. Nonetheless, Diana was trained as a warrior and had no compunction against using deadly force when called for. Diana often dealt with war, injustice, inequality, death, and conflicts involving the Olympian Gods. ' },
];
